version: "3.3"
services:
    app:
        build:
            context: .
        environment:
            - PORT=$PORT
            - HOST=$HOST
            - CSRF_ENABLED=$CSRF_ENABLED
            - DEBUG=$DEBUG
            - SECRET_KEY=$SECRET_KEY
            - DATABASE_HOST=$DATABASE_HOST
            - DATABASE_PORT=$DATABASE_PORT
            - DATABASE_NAME=$DATABASE_NAME
            - DATABASE_USER=$DATABASE_USER
            - DATABASE_PASSWORD=$DATABASE_PASSWORD
            - SQLALCHEMY_ECHO=$SQLALCHEMY_ECHO
            - SQLALCHEMY_TRACK_MODIFICATIONS=$SQLALCHEMY_TRACK_MODIFICATIONS
            - MIGRATION_PATH=$MIGRATION_PATH
        ports:
            - $COMPUTER_PORT:$PORT
        volumes:
            - migration-volume:$MIGRATION_PATH
    postgres:
        image: postgres:latest
        ports:
            - $DATABASE_COMPUTER_PORT:$DATABASE_PORT
        environment:
            - POSTGRES_PASSWORD=$DATABASE_PASSWORD
            - POSTGRES_USER=$DATABASE_USER
            - POSTGRES_DB=$DATABASE_NAME
        volumes:
            - data-volume:/var/lib/postgres
volumes:
  data-volume:
  migration-volume: