"""empty message

Revision ID: 0a37b7f6030f
Revises: 3d7cab602154
Create Date: 2020-04-22 20:20:38.384457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a37b7f6030f'
down_revision = '3d7cab602154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_relation_tag',
    sa.Column('tag_id', sa.String(length=40), nullable=False),
    sa.Column('article_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_relation_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
