"""empty message

Revision ID: 3d7cab602154
Revises: a3b92f94b557
Create Date: 2020-04-21 21:18:40.988224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7cab602154'
down_revision = 'a3b92f94b557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remove_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('article_id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
