"""empty message

Revision ID: bc4dff66578c
Revises: 
Create Date: 2020-04-20 13:31:47.153252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4dff66578c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('name', sa.Enum('ADMIN', 'USER', name='rolename'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remove_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='rolename'), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['role.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'remove_date', name='unique_user_email')
    )
    op.create_table('article',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remove_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_publish', sa.Boolean(), nullable=False),
    sa.Column('writer', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['writer'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
