"""empty message

Revision ID: fb7db56ce67d
Revises: 86e62eebeb24
Create Date: 2020-05-11 11:27:17.129776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7db56ce67d'
down_revision = '86e62eebeb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('subtitle', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'subtitle')
    # ### end Alembic commands ###
